const ResponseMessage = {
    REGISTERED : "Registered successfully",
    LOGIN : "Login successfully",
    DATABASE_CONNECTED: "Database connected",
    USER_ALREADY_EXIST: "User Already exist",
    ADMIN_ALREADY_EXIST: "Admin Already exist",
    ADMIN_ROLE: "Admin role data",
    ADMIN_NOT_FOUND: "Admin not found",
    USER_CREATED: "User registered successfully",
    ADMIN_CREATED: "Admin registered successfully",
    BAD_REQUEST: "Bad request",
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_LOGGED_IN: "User loggedIn",
    ADMIN_LOGGED_IN: "Admin loggedIn",
    PLEASE_USE_VALID_PASSWORD: "Please enter a valid password",
    PASSWORD_REQUIRED: "password is required",
    ENTER_EMAIL_PASSWORD: "Please enter email and mobileNumber",
    USER_LOGOUT: "User logged out",
    ADMIN_LOGOUT: "Admin logged out",
    USER_NOT_EXIST: "User not exist",
    ADMIN_NOT_EXIST: "Admin not exist",
    USER_LIST: "Users list fetched",
    USER_WALLET_DETAIL : "Wallet detail fetched",
    USER_UPDATED: "User updated successfully",
    ADMIN_UPDATED: "Admin updated successfully",
    OTP_SEND: "OTP has been sent to your email",
    OTP_RESEND: "OTP resent successfully",
    REFERRAL_CODE_NOT_FOUND: "Referral code not found",
    RESET_PASSWORD: "Your password has been reset",
    RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
    SOMETHING_WENT_WRONG: "Something went wrong",
    ACCOUNT_NOT_EXIST: "Account not exist",
    VERIFICATION_COMPLETED: "OTP has been verified",
    LOGIN_SUCCESS : "User login suceessfully",
    INVALID_OTP: "Invalid otp",
    INVALID_PASSWORD: "Invalid password",
    OTP_NOT_VERIFY: "Invalid otp",
    USER_NOT_VERIFY: "User not verify",
    PASSWORD_CHANGED: "Password has been changed",
    OLD_PASSWORD_WORNG: "Old password is wrong",
    OLD_PASSWORD_SAME: "Old and new password should not be same",
    SINGLE_USER: "Single user fetched",
    YOU_ENTER_WRONG_PASSWORD: "You enter wrong old password",
    USER_NOT_FOUND: "User not found",
    USER_DELETED: "User deleted successfully",
    ENTER_VALID_ID: "Enter valid id",
    FAILED_TO_CREATED: "Failed to created",
    TOKEN_NOT_AUTHORIZED: "Token not authorized",
    TOKEN_NOT_VALID_AUTHORIZED: "Token not valid authorized",
    PASSWORD_AND_CONFIRM_PASSWORD: "Password and confirm password not match",
    DATA_NOT_FOUND: "Data not found",
    SENT_OTP_ON_YOUR_MOBILE : "Sent otp on your mobile",
    USER_CREATE_SENT_OTP_ON_YOUR_EMAIL : "Account has been created. OTP sent to your email address.",
    ALREADY_REGISTER_VERIFY_EMAIL : "OTP has been sent to your email. Please verify the OTP to log in",
    THIS_USER_IS_DEACTIVATED : "This user is deactivated",
    DEACTIVATED_USER : "Your account has been deactivated.To Activate your account please contact to admin",
    MPIN_ALREADY_USE : "MPIN is already in use",
    OLD_MPIN_WRONG : "Please use valid old Mpin",
    INVALID_MPIN : "Invalid MPIN",
    DATA_GET : "Get data",
    SOME_ERROR_OCCUR : "Some error occur",
    EMAIL_ALREADY_EXIST : "Email already exist", 
    OTP_SENT_TO_BOTH : "Otp sent successfully",
    MOBILENUMBER_ALREADY_EXIST : "Mobile number already exist ",
    PROVIDED_DATA_ALREADY_EXIST : "Provided data already exist ",
    USER_DEACTIVATED : "User deactivate successfully ",
    DATA_FETCHED : "Dashboard data fetched ",
    DATA_NOT_CREATED : "Data not created ",
    DATA_CREATED : "Data created ",
    DATA_UPDATED : "Data updated ",
    DATA_DELETED : "Data deleted ",
    GUEST_LOGIN : "Guest logged in",
    TRANSCATION_DATA_GET : "Transcation detail fetched ",
    HOW_TO_WORK_REFERRAL_CREATED : "How to work referral code created",
    HOW_TO_WORK_REFERRAL_UPDATED : "How to work referral code updated",
    PRIVACY_POLICY_UPDATED : "Privacy policy updated",
    PRICAY_NOT_FOUND : "Privacy policy not found",
    PRIVACY_POLICY_ADDED : "Privacy policy added",
    RULE_ADDED : "Rule added",
    RULE_UPDATE : "Rule updated",
    TERMS_ADDED : "Rule added",
    TERMS_UPDATED : "Rule update",
    CMS_DETAILS : "Cms details fetched",
    UNAUTHORIZED : "Uuauthorized",
    GET_ALL_QUERY : "All queries fetched",
    GAME_RATING_AVERAGE : "Game rating fetched",
    GAME_RATING_NOT_FOUND : "Game rating not found",
    WALLET_DISCONNECTED : "Wallet Disconnected",
    GAME_ADDED : "Game created successfully", 
    GAME_EXIST : "Game already exist", 
    EMAIL_PASSWORD_VERIFY : "Please verify otp to update profile ", 
    PROFILE_UPDATED : "Profile updated successfully", 
    EMAIL_ALREADY_EXIST : "Email is already in use please use another",
    SET_PASSWORD : "Password set successfully",
    SET_PASSWORD_ALREADY : "Password already set",
    SET_NOT_PASSWORD : "Password not set",
    VERIFY_LINK_EXPIRE : "Tisk link has been expired",
    QUERY_CREATED : "Query created successfully",
    QUERY_UPDATED : "Query updated successfully",
    QUERY_DELETED : "Query deleted successfully",
    QUERY_NOT_FOUND : "Query deleted successfully",
    GAME_CREATED : "Game created successfully",
    GAME_GET : "Game get successfully",
    GAME_GET_ALL : "Game all get successfully",
    GAME_UPDATED : "Game updated successfully",
    GAME_DELETED : "Game deleted successfully",
    GAME_ACTIVE : "Game active successfully",
    GAME_DEACTIVE : "Game deactive successfully",
    GAME_NOT_FOUND : "Game not found",
    GAME_RULES_CREATED : "Game rules created successfully",
    GAME_RULES_GET : "Game rules get successfully",
    GAME_RULES_GET_ALL : "Game rules all get successfully",
    GAME_RULES_UPDATED : "Game rules updated successfully",
    GAME_RULES_DELETED : "Game rules deleted successfully",
    GAME_RULES_NOT_FOUND : "Game rules not found successfully",
    GET_RATING : "Get ratings",
    RATING_DELETED : "Ratings deleted successfully",
    GET_WITHDRAWAL : "Get withdrawal",
    WITHDRAWAL_UPDATED : "Withdrawal updated successfully",
    WITHDRAWAL_NOT_FOUND : "Withdrawal not found",
    SETTING_CREATED : "Setting created successfully",
    SETTING_UPDATED : "Setting updated successfully",
    SETTING_DELETED : "Setting deleted successfully",
    SETTING_GET : "Setting get successfully",
    WALLET_CREATED : "Wallet created successfully",
    WALLET_UPDATED : "Wallet updated successfully",
    WALLET_DELETED : "Wallet deleted successfully",
    WALLET_GET : "Wallet get successfully",
    WALLET_NOT_FOUND : "Wallet not found",
    RATING_CREATED : "Rating created successfully",
    RATING_UPDATED : "Rating updated successfully",
    RATING_DELETED : "Rating deleted successfully",
    RATING_GET : "Rating get successfully",
    RATING_NOT_FOUND : "Rating not found",
    TRANSCTION_CREATED : "Transction created successfully",
    TRANSCTION_UPDATED : "Transction updated successfully",
    TRANSCTION_DELETED : "Transction deleted successfully",
    TRANSCTION_GET : "Transction get successfully",
    TRANSCTION_NOT_FOUND : "Transction not found",
    // WITHDRAWAL_CREATED : "Withdrawal created successfully",
    WITHDRAWAL_CREATED : "Your withdraw request is send to admin",
    WITHDRAWAL_UPDATED : "Withdrawal updated successfully",
    WITHDRAWAL_DELETED : "Withdrawal deleted successfully",
    WITHDRAWAL_GET : "Withdrawal get successfully",
    WITHDRAWAL_NOT_FOUND : "withdrawal not found",
    RAFERRAL_NOT_FOUND : "Referral not found",
    USER_ACTIVATED : "User activated successfully",
    USER_DEACTIVATED : "User deactivated successfully",
    FAILED_TO_CREATE: "Failed to created",
    FAILED_TO_UPDATE: "Failed to updated",
    FAILED_TO_DELETE: "Failed to delete",
    FAILED_TO_FETCH: "Failed to fetch",
    NOTIFICATION_TITLE_EXITS : "Notification title already exits",
    NOTIFICATION_CREATED : "Notification created successfully",
    NOTIFICATION_UPDATED : "Notification updated successfully",
    NOTIFICATION_DELETED : "Notification deleted successfully",
    NOTIFICATION_GET : "Notification get successfully",
    NOTIFICATION_NOT_FOUND : "Notification not found",
    USER_DISABLE_BY_ADMIN : "User disable by admin",
    CURRENCY_CONVERTED : "Currency converted successfully",
    WINNER_DECLARE_MANUAL : "Winner will be announced soon",
    WINNER_DECLARE_AUTO : "Winner will declare automatically",
    INSUFFICIENT_BALANCE : "Insufficient balance in your account.",
    GAME_PERIOD_OVER : "Game period not found.",
    GAME_PERIOD_GET : "Get game period.",
    LOSSER : "You are losser",
    NUMBER_WINNER : "Victory Alert! The Winning number is",
    COLOUR_WINNER : "Victory Alert! The Winning Color is",
    NUMBER_BET_CRETED : "Bet add successfully",
    COLOUR_BET_CRETED : "Bet add successfully",
    ALREADY_WIN : "This period ID is already win",
    NUMBER_BET_GET : "Get number bet successfully.",
    NUMBER_BET_NOT_FOUND : "Number bet not found.",
    NUMBER_BET_ID : "Number bet id is required",
    NUMBER_BET_DELETED : "Number deleted successfully.",
    VALID_BET_AMOUNT : "Enter valid amount",
    TYPE_REQUIRED : "Type is required",
    NUMBER_RESULT : "Get numbet bet result successfully",
    COLOUR_RESULT : "Get colour bet result successfully",
    GAME_TYPE_REQUIRED : "Game type is required",
    COLOR_USER_LIST : "Get colour list successfully",
    CMMUNITY_BET_CRETED : "Community bet add successfully",
    CMMUNITY_BET_GET : "Get community bets successfully",
    CMMUNITY_BET_GET_LAST_DAY : "Get last day bets of community betting",
    CMMUNITY_BET_GET_LIVE_DATA : "Get live bets of community betting",
    ROLE_EXIST : "Role already exits",
    ROLE_CREATED : "Role created successfully",
    ROLE_UPDATED : "Role updated successfully",
    ROLE_GET : "Role get successfully",
    ROLE_LIST : "Role list get successfully",
    ROLE_DELETE : "Role deleted successfully",
    PERMISSION_EXIST : "Permission already exits",
    PERMISSION_CREATED : "Permission created successfully",
    PERMISSION_NOT_CREATED : "Permission  not created",
    PERMISSION_UPDATED : "Permission updated successfully",
    PERMISSION_NOT_UPDATED : "Permission not updated",
    PERMISSION_GET : "Permission get successfully",
    PERMISSION_LIST : "Permission list get successfully",
    PERMISSION_DELETE : "Permission deleted successfully",
    DELETED_ALL_PERMISSION : "All Permission deleted successfully",
    PERMISSION_NOT_DELETED : "Permission not deleted",
    PERMISSION_NOT_FOUND : "Permission not found",
    PERMISSION_ACTIVE : "Permission active successfully",
    PERMISSION_DEACTIVE : "Permission deactive successfully",
}

export { ResponseMessage };
