const ResponseMessage = {
    DATABASE_CONNECTED: "Database connected",
    USER_ALREADY_EXIST: "User Already exist",
    ADMIN_ALREADY_EXIST: "Admin Already exist",
    USER_CREATED: "User registered successfully",
    ADMIN_CREATED: "Admin registered successfully",
    BAD_REQUEST: "Bad request",
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_LOGGED_IN: "User loggedIn",
    ADMIN_LOGGED_IN: "Admin logged in successfully.",
    PLEASE_USE_VALID_PASSWORD: "Please enter a valid password",
    PASSWORD_REQUIRED: "password is required",
    ENTER_EMAIL_PASSWORD: "Please enter email and mobileNumber",
    USER_LOGOUT: "User logged out",
    ADMIN_LOGOUT: "Admin logged out",
    USER_NOT_EXIST: "User not exist",
    WALLET_NOT_EXIST: "Wallet not exist",
    ADMIN_NOT_EXIST: "Admin not exist",
    USER_LIST: "Users list fetched",
    USER_WALLET_DETAIL: "Wallet detail fetched",
    USER_UPDATED: "User updated successfully",
    ADMIN_UPDATED: "Admin updated successfully",
    OTP_SEND: "OTP has been sent to your email",
    OTP_RESEND: "OTP resent successfully",
    REFERRAL_CODE_NOT_FOUND: "Referral code not found",
    RESET_PASSWORD: "Password has been reset successfully.",
    RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
    SOMETHING_WENT_WRONG: "Something went wrong",
    ACCOUNT_NOT_EXIST: "Account not exist",
    VERIFICATION_COMPLETED: "OTP has been verified",
    LOGIN_SUCCESS: "User login successfully",
    INVALID_OTP: "Invalid otp",
    INVALID_PASSWORD: "Invalid password",
    INVALID_TYPE: "Invalid type",
    OTP_NOT_VERIFY: "Invalid otp",
    USER_NOT_VERIFY: "User is not verify",
    PASSWORD_CHANGED: "Password is changed successfully.",
    OLD_PASSWORD_WORNG: "Old password is wrong",
    OLD_PASSWORD_SAME: "Old and new password should not be same",
    SINGLE_USER: "Single user fetched",
    YOU_ENTER_WRONG_PASSWORD: "You enter wrong old password",
    USER_NOT_FOUND: "User not found",
    USER_DELETED: "User deleted successfully",
    ENTER_VALID_ID: "Enter valid id",
    FAILED_TO_CREATED: "Failed to created",
    TOKEN_NOT_AUTHORIZED: "Token not authorized",
    TOKEN_NOT_VALID_AUTHORIZED: "Token not valid authorized",
    PASSWORD_AND_CONFIRM_PASSWORD: "Password and confirm password not match",
    DATA_NOT_FOUND: "Data not found",
    SENT_OTP_ON_YOUR_MOBILE: "Sent otp on your mobile",
    USER_CREATE_SENT_OTP_ON_YOUR_EMAIL: "OTP has been sent to your email address.",
    ALREADY_REGISTER_VERIFY_EMAIL: "OTP has been sent to your email. Please verify the OTP to log in",
    THIS_USER_IS_DEACTIVATED: "This user is deactivated",
    DEACTIVATED_USER: "Your account has been deactivated.To Activate your account please contact to admin",
    MPIN_ALREADY_USE: "MPIN is already in use",
    OLD_MPIN_WRONG: "Please use valid old Mpin",
    INVALID_MPIN: "Invalid MPIN",
    DATA_GET: "Get data",
    DASHBOARD_DATA_GET: "Get dashboard data successfully",
    SOME_ERROR_OCCUR: "Some error occur",
    OTP_SENT_TO_BOTH: "Otp sent successfully",
    MOBILENUMBER_ALREADY_EXIST: "Mobile number already exist ",
    PROVIDED_DATA_ALREADY_EXIST: "Provided data already exist ",
    USER_DEACTIVATED: "User deactivate successfully ",
    DATA_FETCHED: "Dashboard data fetched ",
    DATA_NOT_CREATED: "Data not created ",
    DATA_CREATED: "Data created ",
    DATA_UPDATED: "Data updated ",
    DATA_DELETED: "Data deleted ",
    GUEST_LOGIN: "Guest logged in",
    TRANSCATION_DATA_GET: "Transcation detail fetched ",
    HOW_TO_WORK_REFERRAL_CREATED: "How to work referral code created",
    HOW_TO_WORK_REFERRAL_UPDATED: "How to work referral code updated",
    PRIVACY_POLICY_UPDATED: "Privacy policy updated",
    PRICAY_NOT_FOUND: "Privacy policy not found",
    PRIVACY_POLICY_ADDED: "Privacy policy added",
    ABOUT_US_ADDED: "About us add successfully",
    ABOUT_US_UPDATE: "About us update successfully",
    TERMS_ADDED: "Terms And Condition add successfully",
    TERMS_UPDATED: "Terms And Condition update successfully",
    CMS_DETAILS: "Cms details fetched",
    UNAUTHORIZED: "Uuauthorized",
    GET_ALL_QUERY: "All queries fetched",
    GAME_RATING_AVERAGE: "Game rating fetched",
    WALLET_DISCONNECTED: "Wallet Disconnected",
    GAME_ADDED: "Game created successfully",
    COINSETTING_CREATED: "Currency setting created successfully",
    COINSETTING_UPDATED: "Currency setting updated successfully",
    COINSETTING_GET: "Currency setting fetched successfully",
    COINSETTING_LIST: "Currency setting list fetched successfully",
    GAME_EXIST: "Game already exist",
    CURRENCY_EXIST: "Currency already exist",
    EMAIL_PASSWORD_VERIFY: "Please verify otp to update profile ",
    PROFILE_UPDATED: "Profile updated successfully",
    BANK_DETAILS_UPDATED: "Bank details updated successfully",
    EMAIL_ALREADY_EXIST: "Email is already in use please use another",
    SET_PASSWORD: "Password set successfully",
    SET_PASSWORD_ALREADY: "Password already set",
    SET_NOT_PASSWORD: "Password not set",
    VERIFY_LINK_EXPIRE: "Tisk link has been expired",
    QUERY_CREATED: "Query created successfully",
    QUERY_UPDATED: "Query updated successfully",
    QUERY_DELETED: "Query deleted successfully",
    QUERY_NOT_FOUND: "Query not found",
    GAME_CREATED: "Game created successfully",
    GAME_GET: "Game get successfully",
    GAME_GET_ALL: "Game all get successfully",
    GAME_UPDATED: "Game updated successfully",
    GAME_DELETED: "Game deleted successfully",
    GAME_NOT_FOUND: "Game not found successfully",
    GAME_ACTIVE: "Game activated successfully",
    GAME_DEACTIVE: "Game deactivated successfully",
    GAME_MAX_LIMIT: "You have reached maximum game limit",
    GAME_ACTIVE_LIMIT: "You have reached maximum activated game limit",
    GAME_RULES_CREATED: "Game rules created successfully",
    GAME_RULES_GET: "Game rules get successfully",
    GAME_RULES_GET_ALL: "Get all game rules successfully",
    GAME_RULES_UPDATED: "Game rules updated successfully",
    GAME_RULES_DELETED: "Game rules deleted successfully",
    GAME_RULES_NOT_FOUND: "Game rules not found",
    GET_RATING: "Get ratings",
    GET_WITHDRAWAL: "Get withdrawal",
    WITHDRAWAL_UPDATED: "Withdrawal updated successfully",
    WITHDRAWAL_NOT_FOUND: "Withdrawal not found",
    SETTING_NOT_FOUND: "Setting not found",
    SETTING_CREATED: "Setting created successfully",
    SETTING_UPDATED: "Setting updated successfully",
    SETTING_DELETED: "Setting deleted successfully",
    SETTING_GET: "Setting get successfully",
    WALLET_CREATED: "Wallet created successfully",
    WALLET_UPDATED: "Wallet updated successfully",
    WALLET_DELETED: "Wallet deleted successfully",
    WALLET_GET: "Wallet get successfully",
    WALLET_NOT_FOUND: "Wallet not found",
    RATING_CREATED: "Rating created successfully",
    RATING_UPDATED: "Rating updated successfully",
    RATING_DELETED: "Rating deleted successfully",
    RATING_GET: "Rating get successfully",
    RATING_NOT_FOUND: "Rating not found",
    TRANSCTION_CREATED: "Transcation successfully",
    TRANSCTION_UPDATED: "Transction updated successfully",
    TRANSCTION_DELETED: "Transction deleted successfully",
    TRANSCTION_GET: "Transction get successfully",
    TRANSCTION_NOT_FOUND: "Transction not found",
    WITHDRAWAL_CREATED: "Your withdraw request is send to admin",
    WITHDRAWAL_UPDATED: "Withdrawal updated successfully",
    WITHDRAWAL_DELETED: "Withdrawal deleted successfully",
    WITHDRAWAL_GET: "Withdrawal get successfully",
    WITHDRAWAL_REQUEST_SEND: "Withdrawal request send successfully",
    WITHDRAWAL_NOT_FOUND: "withdrawal not found",
    WITHDRAWAL_INVALID: "Invalid withdrawal request",
    INSUFFICIENT_BALANCE: "Insufficient balance in your account.",
    GET_DEPOSIT_AMOUNT: "Deposit amount get successfully",
    RAFERRAL_NOT_FOUND: "Referral not found",
    USER_ACTIVATED: "User activated successfully",
    USER_DEACTIVATED: "User deactivated successfully",
    FAILED_TO_CREATE: "Fail to create",
    FAILED_TO_UPDATE: "Fail to update",
    FAILED_TO_DELETE: "Fail to delete",
    FAILED_TO_FETCH: "There is no content found.",
    REGISTERED: "Registered successfully",
    LOGIN: "Login successfully",
    PASSWORD_SET: "Password set successfully",
    PASSWORD_NOT_SET: "Password has been not set yet",
    REGISTERED_TYPE_NOT_MATCH_FOR_PASSWORD: "You have not registered with password ,kindly login with otp then set password.",
    REGISTERED_TYPE_NOT_MATCH_FOR_OTP: "You have not registered with otp ,kindly login with password.",
    WALLET_CONNECT: "Registered with wallet successfully",
    CURRENCY_CONVERTED: "Currency converted successfully",
    NOTIFICATION_TITLE_EXITS: "Notification title already exits",
    NOTIFICATION_CREATED: "Notification created successfully",
    NOTIFICATION_UPDATED: "Notification updated successfully",
    NOTIFICATION_DELETED: "Notification deleted successfully",
    NOTIFICATION_GET: "Notification get successfully",
    NOTIFICATION_NOT_FOUND: "Notification not found",
    ROLE_EXIST: "Role name already exist",
    ROLE_NOT_FOUND: "Role not found",
    ROLE_CREATED: "Role created successfully",
    ROLE_NOT_CREATED: "Role not created",
    ROLE_UPDATED: "Role updated successfully",
    ROLE_NOT_UPDATED: "Role not update",
    ROLE_GET: "Role fetched successfully",
    ROLE_LIST: "Role list fetched successfully",
    ROLE_DELETE: "Role deleted successfully",
    PERMISSION_EXIST: "Permission name already exist",
    PERMISSION_NOT_FOUND: "Permission not found",
    PERMISSION_CREATED: "Permission created successfully",
    PERMISSION_NOT_CREATED: "Permission not created",
    PERMISSION_UPDATED: "Permission updated successfully",
    PERMISSION_NOT_UPDATED: "Permission not update",
    PERMISSION_GET: "Permission fetched successfully",
    PERMISSION_LIST: "Permission list fetched successfully",
    PERMISSION_DELETE: "Permission deleted successfully",
    PERMISSION_ACTIVE: "Permission active successfully",
    PERMISSION_DEACTIVE: "Permission deactive successfully",
    BANNER_TITLE_EXITS: "Banner title already exits",
    BANNER_CREATED: "Banner created successfully",
    BANNER_UPDATED: "Banner updated successfully",
    BANNER_DELETED: "Banner deleted successfully",
    BANNER_GET: "Banner get successfully",
    BANNER_NOT_FOUND: "Banner not found",
    SUBADMIN_ALREADY_EXITS: "Subdmin already exits",
    SUBADMIN_NOT_FOUND: "Subdmin not found",
    SUBADMIN_CREATED: "Subdmin created successfully",
    SUBADMIN_UPDATED: "Subdmin updated successfully",
    SUBADMIN_DELETED: "Subdmin deleted successfully",
    SUBADMIN_GET: "Subdmin get successfully",
    SUBADMIN_ACTIVE: "Subdmin active successfully",
    SUBADMIN_DEACTIVE: "Subdmin deactive successfully",
    CURRENCY_ALREADY_EXITS: "Currency already exits",
    CURRENCY_NOT_FOUND: "Currency not found",
    CURRENCY_CREATED: "Currency created successfully",
    CURRENCY_UPDATED: "Currency updated successfully",
    CURRENCY_DELETED: "Currency deleted successfully",
    CURRENCY_GET: "Currency get successfully",
    CURRENCY_COIN_NOT_FOUND: "Coin not found",
    CURRENCY_COIN_CREATED: "Coin created successfully",
    CURRENCY_COIN_UPDATED: "Coin updated successfully",
    CURRENCY_COIN_DELETED: "Coin deleted successfully",
    CURRENCY_COIN_GET: "Coin get successfully",
    WITHDRAWAL_REQUEST_ACCEPTED : "Withdrawal request accepted successfully",
    WITHDRAWAL_REQUEST_REJECTED : "Withdrawal request rejected successfully",
    NUMBER_BET_CRETED : "Number bet created successfully",
    NUMBER_BET_UPDATED : "Number bet updated successfully",
    NUMBER_BET_DELETED : "Number bet deleted successfully",
    NUMBER_BET_GET : "Get number bet successfully",
    NUMBER_BET_NOT_FOUND : "Number bet not found",
    NUMBER_BET_ID : "Number bet id is required",
    GAME_TIME_CREATED : "Game time created successfully",
    GAME_TIME_UPDATED : "Game time updated successfully",
    GAME_TIME_GET : "Get game time successfully",
    GAME_TIME_NOT_FOUND : "Get game time not found.",
    COLOUR_BET_CRETED : "Colour bet created successfully",
    INSUFFICIENT_BALANCE_USER:"You don't have sufficient balance",
    COLOUR_RESULT:"Here it is details of colour betting game"
}

export { ResponseMessage }