const ResponseMessage = {
    DATABASE_CONNECTED: "Database connected",
    USER_ALREADY_EXIST: "User Already exist",
    ADMIN_ALREADY_EXIST: "Admin Already exist",
    USER_CREATED: "User registered successfully",
    ADMIN_CREATED: "Admin registered successfully",
    BAD_REQUEST: "Bad request",
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_LOGGED_IN: "User loggedIn",
    ADMIN_LOGGED_IN: "Admin loggedIn",
    PLEASE_USE_VALID_PASSWORD: "Please enter a valid password",
    PASSWORD_REQUIRED: "password is required",
    ENTER_EMAIL_PASSWORD: "Please enter email and mobileNumber",
    USER_LOGOUT: "User logged out",
    ADMIN_LOGOUT: "Admin logged out",
    USER_NOT_EXIST: "User not exist",
    ADMIN_NOT_EXIST: "Admin not exist",
    USER_LIST: "Users list fetched",
    USER_WALLET_DETAIL : "Wallet detail fetched",
    USER_UPDATED: "User updated successfully",
    ADMIN_UPDATED: "Admin updated successfully",
    OTP_SEND: "OTP has been sent to your email",
    OTP_RESEND: "OTP resent successfully",
    REFERRAL_CODE_NOT_FOUND: "Referral code not found",
    RESET_PASSWORD: "Your password has been reset",
    RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
    SOMETHING_WENT_WRONG: "Something went wrong",
    ACCOUNT_NOT_EXIST: "Account not exist",
    VERIFICATION_COMPLETED: "OTP has been verified",
    LOGIN_SUCCESS : "User login suceessfully",
    INVALID_OTP: "Invalid otp",
    INVALID_PASSWORD: "Invalid password",
    OTP_NOT_VERIFY: "Invalid otp",
    USER_NOT_VERIFY: "User not verify",
    PASSWORD_CHANGED: "Password has been changed",
    OLD_PASSWORD_SAME: "Old and new password should not be same",
    SINGLE_USER: "Single user fetched",
    YOU_ENTER_WRONG_PASSWORD: "You enter wrong old password",
    USER_NOT_FOUND: "User not found",
    ENTER_VALID_ID: "Enter valid id",
    FAILED_TO_CREATED: "Failed to created",
    TOKEN_NOT_AUTHORIZED: "Token not authorized",
    TOKEN_NOT_VALID_AUTHORIZED: "Token not valid authorized",
    PASSWORD_AND_CONFIRM_PASSWORD: "Password and confirm password not match",
    DATA_NOT_FOUND: "Data not found",
    SENT_OTP_ON_YOUR_MOBILE : "Sent otp on your mobile",
    USER_CREATE_SENT_OTP_ON_YOUR_EMAIL : "Account has been created. OTP sent to your email address.",
    ALREADY_REGISTER_VERIFY_EMAIL : "OTP has been sent to your email. Please verify the OTP to log in",
    THIS_USER_IS_DEACTIVATED : "This user is deactivated",
    MPIN_ALREADY_USE : "MPIN already use",
    OLD_MPIN_WRONG : "Old MPIN worng",
    INVALID_MPIN : "Invalid MPIN",
    DATA_GET : "Get data",
    SOME_ERROR_OCCUR : "Some error occur",
    EMAIL_ALREADY_EXIST : "Email already exist", 
    OTP_SENT_TO_BOTH : "Otp sent successfully",
    MOBILENUMBER_ALREADY_EXIST : "Mobile number already exist ",
    PROVIDED_DATA_ALREADY_EXIST : "Provided data already exist ",
    USER_DEACTIVATED : "User deactivate successfully ",
    DATA_FETCHED : "Dashboard data fetched ",
    DATA_NOT_CREATED : "Data not created ",
    DATA_CREATED : "Data created ",
    DATA_UPDATED : "Data updated ",
    DATA_DELETED : "Data deleted ",
    GUEST_LOGIN : "Guest logged in",
    TRANSCATION_DATA_GET : "Transcation detail fetched ",
    HOW_TO_WORK_REFERRAL_CREATED : "How to work referral code created",
    HOW_TO_WORK_REFERRAL_UPDATED : "How to work referral code updated",
    PRIVACY_POLICY_UPDATED : "Privacy policy updated",
    PRICAY_NOT_FOUND : "Privacy policy not found",
    PRIVACY_POLICY_ADDED : "Privacy policy added",
    RULE_ADDED : "Rule added",
    RULE_UPDATE : "Rule updated",
    TERMS_ADDED : "Rule added",
    TERMS_UPDATED : "Rule update",
    CMS_DETAILS : "Cms details fetched",
    UNAUTHORIZED : "Uuauthorized",
    GET_ALL_QUERY : "All queries fetched",
    GAME_RATING_AVERAGE : "Game rating fetched",
    WALLET_DISCONNECTED : "Wallet Disconnected",
    GAME_ADDED : "Game created successfully", 
    GAME_EXIST : "Game already exist", 
    EMAIL_PASSWORD_VERIFY : "Please verify otp to update profile ", 
    PROFILE_UPDATED : "Profile updated successfully", 
    EMAIL_ALREADY_EXIST : "Email is already in use please use another"
}

export { ResponseMessage }